.\"
.\" madplay - MPEG audio decoder and player
.\" Copyright (C) 2000-2004 Robert Leslie
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.\" $Id$
.\"
.TH MADTAG 1 "14 November 2001" "MAD" "MPEG Audio Decoder"
.SH NAME
madtag \- display or modify ID3 tags
.SH SYNOPSIS
.B madtag
.RI [ options ]
.I file
\&...
.SH DESCRIPTION
.B madtag
is ...
.SH OPTIONS
.SS Miscellaneous
.TP
.BR \-V " or " \-\-version
Display the effective version for
.B madtag
and exit.
.TP
.BR \-h " or " \-\-help
Display a usage message and exit.
.SH CONFORMING TO
The ID3 tag manipulation library used by
.B madtag
conforms to the ID3v2.4.0 informal standard.
.SH AUTHOR
Robert Leslie <rob@mars.org>
.SH SEE ALSO
.BR madplay (1)
