struct xdriverdata {
  Display *dp;
  Window wi;
  Pixmap pi;
  XSetWindowAttributes attr;
  int fontheight;
  int fontwidth;
  GC normalGC, dimGC, boldGC, currGC, specialGC;
  int cvisible;
  GC blackGC;
  Colormap cmap;
  int screen;
  long bold, normal, dim, black, special;
  int width;
  int height;
  XFontStruct *font_s;
  int Xpos;
  int pixmapmode;
  int Ypos;
  int mmwidth, mmheight;
  unsigned char *previoust, *previousa;
  int font;
  int pixelwidth, pixelheight;
};
