
EE_BIN     = example.elf

EE_LIBS   += -L$(PS2SDK)/ports/lib -L$(GSKIT)/lib/ 
EE_LIBS   += -lmikmod -lgskit -ldmakit -laudsrv
EE_INCS   += -I../include -Isrc -I$(PS2SDK)/ports/include -I$(GSKIT)/include



# -- PS2 specific source code --
EE_OBJS   = example.o

all:    $(EE_BIN)
	$(EE_STRIP) $(EE_BIN)

clean:
	rm -f $(EE_BIN) $(EE_OBJS)

run:
	ps2client -h 192.168.0.10 execee host:$(EE_BIN)

reset:
	ps2client -h 192.168.0.10 reset


include $(PS2SDK)/Defs.make
include ../Makefile.eeglobal
