##
# Makefile for PS2 port of libconfig
##

EE_INCS +=
EE_CFLAGS +=
EE_LDFLAGS +=
EE_ASFLAGS +=

EE_LIB = libconfig.a
EE_OBJS = grammar.o scanner.o libconfig.o
EE_LIBS =

all: $(EE_LIB)

install: all
	mkdir -p $(PS2SDK)/ports/include
	mkdir -p $(PS2SDK)/ports/lib
	cp -f $(EE_LIB) $(PS2SDK)/ports/lib
	cp -f libconfig.h $(PS2SDK)/ports/include

clean:
	rm -f $(EE_LIB) $(EE_OBJS)

rebuild: clean all

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal
