# ps2aalib
# aalib ps2port by brice rouanet
# tmator@gmail.com
# GPL V2

all :
	$(MAKE) -C src all

sample: all
	$(MAKE) -C test all

clean :
	$(MAKE) -C src clean
	$(MAKE) -C test clean

install: all
	$(MAKE) -C src install
