libs:
	make -C ode/src 
	make -C drawstuff/src 
	make -C ode/src install
	make -C drawstuff/src install

test:
	make -C ode/test

clean:
	make -C ode/src clean
	make -C drawstuff/src clean
	make -C ode/test clean
